# Directories arguments
data_dir: "/media/DATA/UnrealLandingDataset/AirSimCollectData/" # "full_cityscapes_res"
exp_dir:  "fcn8s_mobilenet"
out_dir:  "fcn8s_mobilenet"

# Data arguments
img_height:   512
img_width:    512 #1024
num_channels: 3
num_classes:  18 # 20

# Train arguments
num_epochs: 100 #200
batch_size: 8 #4
shuffle: True
data_mode: "experiment"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: False
random_cropping: False
freeze_encoder: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

